name: to_do_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_datetime_picker_plus: ^2.0.1
  uuid: ^4.0.0
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.4
  path_provider: ^2.1.1
  easy_localization: ^3.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
